# Questionário ativo da Pesquisa de Satisfação de Franqueados.
# Cada campanha nova grava uma cópia (snapshot) dessa lista no momento da criação,
# então mudar este arquivo não altera campanhas já criadas — só as futuras.

QUESTIONS: list[dict] = [
    {"id": "treinamento_inicial", "categoria": "Suporte e Treinamento", "tipo": "escala5",
     "texto": "O treinamento inicial me preparou bem para operar a franquia."},
    {"id": "suporte_operacional", "categoria": "Suporte e Treinamento", "tipo": "escala5",
     "texto": "Recebo suporte operacional (dúvidas do dia a dia) de forma rápida e eficiente."},
    {"id": "suporte_tecnico", "categoria": "Suporte e Treinamento", "tipo": "escala5",
     "texto": "O suporte técnico/sistemas resolve meus problemas com agilidade."},
    {"id": "comunicacao_clara", "categoria": "Comunicação e Relacionamento", "tipo": "escala5",
     "texto": "A franqueadora se comunica de forma clara e frequente sobre novidades e mudanças."},
    {"id": "feedback_ouvido", "categoria": "Comunicação e Relacionamento", "tipo": "escala5",
     "texto": "Minhas sugestões e feedbacks são ouvidos e levados em consideração."},
    {"id": "relacionamento_lideranca", "categoria": "Comunicação e Relacionamento", "tipo": "escala5",
     "texto": "Sinto que tenho um bom relacionamento com a liderança da Piaseg."},
    {"id": "marketing_negocios", "categoria": "Marketing e Geração de Negócios", "tipo": "escala5",
     "texto": "As ações de marketing da franqueadora ajudam a gerar novos negócios para minha unidade."},
    {"id": "materiais_qualidade", "categoria": "Marketing e Geração de Negócios", "tipo": "escala5",
     "texto": "Os materiais e campanhas fornecidos têm boa qualidade."},
    {"id": "sistemas_facilitam", "categoria": "Sistemas e Ferramentas", "tipo": "escala5",
     "texto": "Os sistemas disponibilizados (ex: Piazinho, sistema financeiro) facilitam meu trabalho."},
    {"id": "ferramentas_atendem", "categoria": "Sistemas e Ferramentas", "tipo": "escala5",
     "texto": "As ferramentas de gestão atendem às necessidades da minha operação."},
    {"id": "retorno_financeiro", "categoria": "Retorno Financeiro / Viabilidade", "tipo": "escala5",
     "texto": "O modelo de negócio da Piaseg oferece um retorno financeiro satisfatório."},
    {"id": "custos_justos", "categoria": "Retorno Financeiro / Viabilidade", "tipo": "escala5",
     "texto": "Os custos e taxas cobrados pela franqueadora são justos em relação ao que recebo em troca."},
    {"id": "orgulho_marca", "categoria": "Cultura e Marca", "tipo": "escala5",
     "texto": "Tenho orgulho de fazer parte da rede Piaseg."},
    {"id": "valores_alinhados", "categoria": "Cultura e Marca", "tipo": "escala5",
     "texto": "Os valores da Piaseg estão alinhados com a forma como conduzo meu negócio."},
    {"id": "satisfacao_geral", "categoria": "Satisfação Geral", "tipo": "escala5",
     "texto": "De forma geral, estou satisfeito(a) como franqueado(a) Piaseg."},
    {"id": "nps", "categoria": "Satisfação Geral", "tipo": "nps",
     "texto": "Em uma escala de 0 a 10, o quanto você recomendaria a Piaseg para outro empreendedor?"},
    {"id": "pontos_fortes", "categoria": "Comentários", "tipo": "texto",
     "texto": "O que a Piaseg faz muito bem, na sua opinião?"},
    {"id": "pontos_melhorar", "categoria": "Comentários", "tipo": "texto",
     "texto": "O que a Piaseg poderia melhorar?"},
    {"id": "comentario_livre", "categoria": "Comentários", "tipo": "texto",
     "texto": "Deixe aqui sugestões, críticas ou elogios livres."},
]
